language: python
os:
  - linux
python:
  - '3.6'
install:
  - pip install pytest-pep8 pytest-cov
  - pip install codecov
  - pip install elasticsearch_dsl certstream pyahocorasick tldextract
  - pip install -e .[tests]
services:
  - elasticsearch
before_script:
  - curl 'http://localhost:9200'
script:
  - pytest --pep8 -m pep8 certstream_analytics/
  - PYTHONPATH=$PWD:$PYTHONPATH pytest --cov=./ tests/
after_script:
  - curl 'http://localhost:9200/_cat/indices?v'
after_success:
  - codecov
