language: python
os:
  - linux
python:
  - '3.6'
before_install:
  - sudo apt-get install -y libenchant-dev
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.0.deb
  - sudo dpkg -i --force-confnew elasticsearch-6.8.0.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch
install:
  - pip install --upgrade pytest
  - pip install pytest-pep8 pytest-cov
  - pip install codecov
  - pip install elasticsearch_dsl certstream pyahocorasick tldextract wordsegment pyenchant idna confusable-homoglyphs
  - pip install git+https://github.com/casics/nostril.git
  - pip install -e .[tests]
services:
  - elasticsearch
before_script:
  - sleep 10
  - curl 'http://localhost:9200'
script:
  - pytest --pep8 -m pep8 certstream_analytics/
  - PYTHONPATH=$PWD:$PYTHONPATH pytest --cov=./ tests/
after_script:
  - curl 'http://localhost:9200/_cat/indices?v'
after_success:
  - codecov
