language: python
os:
  - linux
python:
  - '3.7'
before_install:
  - sudo apt-get install -y libenchant-dev
  - sudo apt-get install -y apt-transport-https
  - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
  - sudo apt-get update && sudo apt-get remove -y elasticsearch
  - sudo apt-get install -y elasticsearch
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch start
install:
  - pip install --upgrade pytest
  - pip install pytest-pep8 pytest-cov
  - pip install codecov
  - pip install elasticsearch_dsl certstream pyahocorasick tldextract wordsegment pyenchant idna confusable-homoglyphs
  - pip install git+https://github.com/casics/nostril.git
  - pip install https://object-storage.tyo2.conoha.io/v1/nc_2520839e1f9641b08211a5c85243124a/sudachi/SudachiDict_core-20191224.tar.gz
  - pip install flair==0.4.3 # To fix the non-pip dependency issue in tiny-tokenizer
  - pip install -e .[tests]
before_script:
  - sleep 10
  - sudo systemctl -l status elasticsearch
  - curl 'http://localhost:9200'
script:
  - pytest --pep8 -m pep8 certstream_analytics/
  - PYTHONPATH=$PWD:$PYTHONPATH pytest --cov=./ tests/
after_script:
  - curl 'http://localhost:9200/_cat/indices?v'
after_success:
  - codecov
